# Generated by Django 5.2.5 on 2025-08-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0002_alter_contacts_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "Завод"),
                    (1, "Розничная сеть"),
                    (2, "Индивидуальный предприниматель"),
                ],
                max_length=50,
                verbose_name="Тип сети",
            ),
        ),
    ]
